config/routes.rb
Rails.application.routes.draw do
  get 'homes/top'
  devise_for :users
  root to: "homes#top"
   get "home/about" => "homes#about", as: "about"
   resources :books
   post "users/:id" => "users#show"
   resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
   has_one_attached :image
   belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :post_images, dependent: :destroy
         has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

   def after_sign_in_path_for(resource)
     user_path(current_user)
  end

   def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  protect_from_forgery

  def new
    @book = Book.new
  end

def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book.id)
  else
    @books = Book.all
    render :index
    end
    flash[:notice] = "You have created book successfully."
  end

 def index
　  @book = Book.new
　  @books = Book.all
 end

 def show
     @book = Book.find(params[:id])
 end

 def edit
     @book = Book.find(params[:id])
 end

 def update
     @book = Book.find(params[:id])
    if @book.update(book_params)
     redirect_to book_path(@book.id)
    else
      @book = Book.all
      render :edit
    end
     flash[:notice] = "Book was updated successfully."
  end

 def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
 end

  private
  def book_params
    params.require(:book).permit(:title, :body, :image)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery
def new
@user = User.new
@book = Book.new
end

def show
  @user = User.find(params[:id])
  @books = @user.books
  @book = Book.new
end

def create
@User = User.new(user_params)
     if @book.save
      redirect_to user_path(@user.id)
    else
      @users = User.all
      render :new
    end
      flash[:notice] = "Signed in successfully."
   end
end

def index
@user = User.find(params[:id])
end

def edit
@user = User.find(params[:id])
end

def update
@book = Book.find(params[:id])
    if @book.update(book_params)
     redirect_to book_path(user.id)
    else
    render :index
    end
      flash[:notice] = "Book was updated successfully."

    private

  def book_params
    params.require(:book).permit(:title, :opinion)
  end
end

  def destroy
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
  <body>
  <header>
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
      <li>
        <%= link_to "Home", "/" %>
      <li>
        <%= link_to "Users", user_registration_path %>
      </li>
      <li>
        <%= link_to "Books", new_user_session_path %>
      </li>
      <li>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "Home", "/" %>
      </li>
      <li>
        <%= link_to "About",  about_path %>
      </li>
      <li>
        <%= link_to "Sign up", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "Log in", new_user_session_path %>
      </li>
    <% end %>
  </header>

<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>


  </main>
  <%= yield %>
</body>

app/views/books/edit.html.erb
<%= flash[:notice] %>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<h1>Editing Book</h1>
 <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>opinion</h4>
  <%= f.text_area :opinion %>
  <%= f.submit 'Update Book' %>
  <% end %>

 　 <%= link_to 'show', book_path(@book.id) %>
      |
   <%= link_to 'back', '/books'%>

app/views/books/new.html.erb
<%= flash[:notice] %>
<h1>New Book</h1>
<%= form_with model: @book do |f| %>
  <h4>Image</h4>
  <%= f.file_field :image, accept: "image/*" %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<%= flash[:notice] %>
<h1>Book detail</h1>
<p><%= @book.title %></p>

<p><%= @book.body %></p>


<%= link_to 'Edit', edit_book_path(@book.id), class: "btn bg-success text-white" %>
<%#= link_to "Destroy", destroy_session_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
<% if @book.user == current_user %>
    <%= link_to "Destroy", book_path(@book), method: :delete %>
<% end %>

app/views/homes/about.html.erb
<main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>
</main>

<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/homes/top.html.erb
 <main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1", "maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
   <nav class="navbar navbar-expand-lg navbar-dark text-light bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto justify-content-end">
    <% if user_signed_in? %>
      <li>
        <i class="fas fa-book"></i>
        <%= link_to "Home", "/" %>
      <li>
        <i class="fas fa-users"></i>
        <%= link_to "Users", user_registration_path %>
      </li>
      <li>
        <i class="fas fa-book-open"></i>
        <%= link_to "Books", new_user_session_path %>
      </li>
      <li>
        <i class="fas fa-sign-out-alt"></i>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <i class="fas fa-book"></i>
        <%= link_to "Home", "/" %>
      </li>
      <li>
         <i class="fas fa-paperclip"></i>
        <%= link_to "About",  about_path %>
      </li>
      <li>
         <i class="fas fa-user-plus"></i>
        <%= link_to "Sign up", new_user_registration_path %>
      </li>
      <li>
        <i class="fas fa-user-plus"></i>
        <%= link_to "Log in", new_user_session_path %>
      </li>
    <% end %>
  </header>

 <%= yield %>

<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>
<main>


</body>

app/views/users/edit.html.erb
 <% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
 <h1>Editing Book</h1>

 <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>opinion</h4>
  <%= f.text_area :opinion %>
  <%= f.submit 'Update Book' %>
  <% end %>

 　 <%= link_to 'show', book_path(@book.id) %>
      |
   <%= link_to 'back', '/books'%>

app/views/users/index.html.erb
<main>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
  <table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
    </tr>
    <tr>
      <th>introduction</th>
    </tr>
  </tbody>
</table>

<div class="row">
</div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, local:true do |f| %>
      <h4>Title</h4>
      <%= f.text_field :title %>
      <h4>Body</h4>
      <%= f.text_area :body %>
      <%= f.submit 'Create Book' %>
      <% end %>

  </div>
</form>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Uses</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>
    </div>
  </div>
</div>
</main>

app/views/users/show.html.erb
<main>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
  <table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
    </tr>
    <tr>
      <th>introduction</th>
    </tr>
  </tbody>
</table>

<div class="row">
</div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, local:true do |f| %>
      <p>Title</p>
      <%= f.text_field :title %>
      <p>Opinion</p>
      <%= f.text_area :body %>
      <%= f.submit 'Create Book' %>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>
    </div>
  </div>
</div>
</main>